### ISSUE TITLE
Некорректное обновление сделки

### ISSUE THREAD

**Issue by jabir-sabitov** [sashazenit4/otus-learning#1]
https://github.com/sashazenit4/otus-learning/blob/3de7744ed76597232e2a215427b78a7b235688b4/readme-test.md?plain=1#L13

Почему здесь мы обновляем сделку напрямую через таблицу БД? Разве мы не нарушаем связи между таблицами (т.е. информация о сделке может быть записана в несколько таблиц)? Разве мы не упускаем вызов некоторых событий (например, `OnBeforeCrmDealUpdate`). Переопределённого метода `update` в классе `DealTable` не обнаружил, а сам класс наследуется напрямую от DataManager'a.

**Comment by sashazenit4** [comment]
jabir-sabitov
Привет, поправил последним коммитом и обновил readme-test.md файл своими комментариями

**Comment by jabir-sabitov** [comment]
> jabir-sabitov Привет, поправил последним коммитом и обновил readme-test.md файл своими комментариями

Увидел, но всё же сохраняются ли связи между таблицами? Неужели у битрикса нет более высокоуровнего API для работы со сделками?

**Comment by sashazenit4** [comment]
jabir-sabitov переписал на сервисы, это апи ближе всего к старому ядру

**Comment by jabir-sabitov** [comment]
> jabir-sabitov переписал на сервисы, это апи ближе всего к старому ядру

Вот! Сейчас выглядит как надо. А почему считаешь, что ближе к старому ядру?

**Comment by sashazenit4** [comment]
jabir-sabitov
неправильно выразился, имел в виду функциональность сохранения связей сделки
